export const data = [
  {
    image: "/google.png",
    width: "96px",
    height: "96px",
    company: "Google",
    tag1: "CI/CD",
    tag2: "Semantic testing",
    role: "Software Engineer Intern",
    description:
      "Interned with the Google Pay Client Infrastructure team to enhance developer productivity by creating tools for UI change visualizations within pull requests.",
    link: "https://www.google.com",
  },
  {
    image: "/govtech.png",
    width: "96px",
    height: "96px",
    company: "Govtech",
    tag1: "Full-Stack",
    tag2: "Search",
    role: "Software Engineer Intern",
    description:
      "Contributed to enhancements in the government's SearchSG engine by refining features and improving system responsiveness.",
    link: "https://www.search.gov.sg/",
  },
  {
    image: "/zendesk.png",
    width: "124px",
    height: "96px",
    company: "Zendesk",
    role: "Software Engineer Intern",
    tag1: "DevOps",
    tag2: "Back-End Development",
    description:
      "Facilitated the transition of Zendesk services from AWS EC2 to Kubernetes, enhancing scalability and service reliability, and augmented a Java-based GraphQL server with new functionalities.",
    link: "https://www.zendesk.com",
  },
  {
    image: "/kinexcs.svg",
    width: "509px",
    height: "99px",
    company: "Kinexcs",
    role: "Software Development Intern",
    tag1: "iOS & Android Development",
    tag2: "Full Stack Development",
    description:
      "Engaged in full stack development for a mobile health application using Flutter and Flask, including API development and testing with Docker-enhanced workflows.",
    link: "https://www.kinexcs.com/",
  },
  {
    image: "/amd.svg",
    width: "96px",
    height: "96px",
    company: "Advanced Micro Devices (AMD)",
    role: "Software Development Intern",
    tag1: "Embedded Software",
    tag2: "Characterisation and Debugging",
    description:
      "Developed Java-based system-level test programs for AMD's Enterprise chips, supporting agile product development cycles and improving chip performance.",
    link: "https://www.amd.com/en",
  },
  {
    image: "/psyfinance.png",
    width: "96px",
    height: "96px",
    company: "PsyFinance",
    role: "Software Engineer Intern",
    tag1: "UI/UX",
    tag2: "Front-End development",
    description:
      "Designed and implemented user-centric web applications using ReactJS and TypeScript, significantly enhancing front-end performance and user engagement for over 5000 active users.",
    link: "https://psyfi.io/",
  },
  {
    image: "/bumblebee.png",
    width: "96px",
    height: "96px",
    company: "Bumblebee Autonomous Systems",
    role: "Robotics Engineer",
    tag1: "Robot Operating System",
    tag2: "Maritime Robotics",
    description:
      "Engineered autonomous underwater vehicles from scratch, focusing on design and functionality to excel in research initiatives and competitive environments.",
    link: "https://bumblebee.sg/",
  },
  {
    image: "/nus.png",
    width: "96px",
    height: "115px",
    company: "Robot Design Course",
    role: "Teaching Assistant",
    tag1: "Microcontroller Programming",
    tag2: "Engineering Design",
    description:
      "Guided university students through a comprehensive 12-week robotics design course, focusing on microcontroller programming with Arduino and fostering hands-on engineering skills.",
    link: "https://cde.nus.edu.sg/student-life/cde_club/engin-club/",
  },
  {
    image: "/robomasters.jpg",
    width: "96px",
    height: "96px",
    company: "NUS Robomasters",
    role: "Robotics Engineer",
    tag1: "STM32 Microcontroller Programming",
    tag2: "Robotic Design",
    description:
      "Enhanced robotic capabilities by adapting STM32 microcontroller code for integration with hardware, utilizing RTOS for optimal performance.",
    link: "https://nusrobomaster.com/",
  },
  {
    image: "/seeds.jpg",
    width: "96px",
    height: "96px",
    company: "Seeds of Good Program",
    role: "Coding Instructor",
    tag1: "Programming fundamentals",
    tag2: "Scratch",
    description:
      "Instructed primary and secondary school students in the fundamentals of programming, using Scratch to create interactive web games that fostered a foundational understanding of coding concepts.",
    link: "https://www.nus.edu.sg/alumnet/thealumnus/issue-118/community/oar-highlights/planting-seeds-of-good",
  },
  {
    image: "/engin.jpg",
    width: "96px",
    height: "50px",
    company: "NUS Engineering Club",
    role: "Vice Project Director",
    tag1: "Leadership",
    tag2: "Event Planning",
    description:
      "Led the planning and execution of a two-day orientation camp for over 200 engineering freshmen, coordinating a team of 12 to ensure a smooth and engaging experience for new students.",
    link: "https://cde.nus.edu.sg/student-life/cde_club/engin-club/",
  },
];
