export const data = [
  {
    image: "/google.png",
    width: "96px",
    height: "96px",
    company: "Google",
    role: "Incoming Software Engineer Intern",
    link: "https://www.google.com",
  },
  {
    image: "/zendesk.png",
    width: "124px",
    height: "96px",
    company: "Zendesk",
    role: "Software Engineer Intern",
    tag1: "DevOps",
    tag2: "Back-End Development",
    description:
      "Working on migrating Zendesk EC2 development environments to Kubernetes clusters",
    link: "https://www.zendesk.com",
  },
  {
    image: "/kinexcs.svg",
    width: "509px",
    height: "99px",
    company: "Kinexcs",
    role: "Software Development Intern",
    tag1: "iOS & Android Development",
    tag2: "Full Stack Development",
    description:
      "Worked on Full Stack development of Mobile Application in Flutter as well as building and testing APIs using Flask and Docker",
    link: "https://www.kinexcs.com/",
  },
  {
    image: "/amd.svg",
    width: "96px",
    height: "96px",
    company: "Advanced Micro Devices (AMD)",
    role: "Software Development Intern",
    tag1: "Embedded Software",
    tag2: "Characterisation and Debugging",
    description:
      "Developed system level test programs in Java for AMD’s Enterprise chips, supporting their agile product development",
    link: "https://www.amd.com/en",
  },
  {
    image: "/psyfinance.png",
    width: "96px",
    height: "96px",
    company: "PsyFinance",
    role: "Software Engineer Intern",
    tag1: "UI/UX",
    tag2: "Front-End development",
    description:
      "Designed and developed web applications using ReactJS and TypeScript, optimised front-end performance through better state management and shipped new features to over 5000 users.",
    link: "https://psyfi.io/",
  },
  {
    image: "/bumblebee.png",
    width: "96px",
    height: "96px",
    company: "Bumblebee Autonomous Systems",
    role: "Robotics Engineer",
    tag1: "Robot Operating System",
    tag2: "Maritime Robotics",
    description:
      "Designed autonomous underwater vehicles from the ground-up for research purposes & participation in competitions.",
    link: "https://bumblebee.sg/",
  },
  {
    image: "/nus.png",
    width: "96px",
    height: "115px",
    company: "Robot Design Course",
    role: "Teaching Assistant",
    tag1: "Microcontroller Programming",
    tag2: "Engineering Design",
    description:
      "Guided students in a 12-week robot design and make course which exposed them to C++ micro-controller programming.",
    link: "https://nusmods.com/modules/EG1311/design-and-make",
  },
  {
    image: "/robomasters.jpg",
    width: "96px",
    height: "96px",
    company: "NUS Robomasters",
    role: "Robotics Engineer",
    tag1: "STM32 Microcontroller Programming",
    tag2: "Robotic Design",
    description:
      "Adapted existing STM32 micro-controller code written in C++ and integrated it into sentry robot’s hardware using RTOS.",
    link: "https://nusrobomaster.com/",
  },
  {
    image: "/seeds.jpg",
    width: "96px",
    height: "96px",
    company: "Seeds of Good Program",
    role: "Coding Instructor",
    tag1: "Programming fundamentals",
    tag2: "Scratch",
    description:
      "Taught programming to 50 primary and secondary school students using interactive web games built using Scratch.",
    link: "https://www.nus.edu.sg/alumnet/thealumnus/issue-118/community/oar-highlights/planting-seeds-of-good",
  },
  {
    image: "/engin.jpg",
    width: "96px",
    height: "50px",
    company: "NUS Engineering Club",
    role: "Vice Project Director",
    tag1: "Leadership",
    tag2: "Event Planning",
    description:
      "Led a team of 12 through the planning and execution of a 2-day orientation camp for over 200 incoming freshmen.",
    link: "https://cde.nus.edu.sg/student-life/cde_club/engin-club/",
  },
];
