export { Hero } from "./Hero/Hero";
export { Header } from "./Header";
export { Projects } from "./Projects/Projects";
export { Navbar } from "./Navbar/Navbar";
export { Experiences } from "./Experiences/Experiences";
export { Contact } from "./Contact/Contact";
export { LinkDesktop } from "./Links/Desktop";
export { LinkMobile } from "./Links/Mobile";
export { Code } from "./Code/Code";
